function closefun() {
    var section = document.getElementById("section1");
    section.style.visibility = "hidden";
    var section2 = document.getElementById("section2");
    section2.style.visibility = "hidden";
}
function registerfun() {
    document.getElementById('div2').style.display = 'block';
    document.getElementById('div1').style.display = 'none';
}
function close2fun() {
    var section = document.getElementById("section2");
    section.style.visibility = "hidden";
}
function logfun() {
    document.getElementById('div2').style.display = 'none';
    document.getElementById('div1').style.display = 'block';
}
function registerfun() {
    document.getElementById('div2').style.display = 'block';
    document.getElementById('div1').style.display = 'none';
}

function showForm() {
    var section = document.getElementById("section1");
    section.style.visibility = "visible";
    var section2 = document.getElementById("section2");
    section2.style.visibility = "visible";
}
